export enum EventoType {
  HISTORY = 1,   //EVENTOS QUE PROGRESAN LA HISTORIA
  ACTIVITY = 2,  // EVENTOS QUE SE EJECUTAN COMO ACTIVIDADES RUTINARIAS
  LOCATION = 3,  // EVENTOS QUE SE ACTIVAN AL ENTRAR A LOCATIONS
  CHARACTER =4,  //EVENTOS QUE SE ACTIVAN CON EL NPC
  GLOBAL = 5,   //EVENTOS QUE SE ACTIVAN AL CUMPLISE LAS CONDICIONES

  NONE = 0
}
