export enum EventoType {
  HISTORY = 1,   //EVENTOS QUE PROGRESAN LA HISTORIA
  ACTIVITY = 2,  // EVENTOS QUE SE EJECUTAN COMO ACTIVIDADES RUTINARIAS
  LOCATION = 3,  // EVENTOS QUE SE ACTIVAN AL ENTRAR A LOCATIONS
  GLOBAL = 4,   //EVENTOS QUE SE ACTIVAN AL CUMPLISE LAS CONDICIONES


  VIP1 = 10,
  VIP2 = 20,
  VIP3 = 30,
  VIP4 = 40,



  ERROR = 999,
  NONE = 0
}
