name: Build Electron App

# 1. Definimos cuándo se ejecutará el workflow
on:
  push:
    branches: [ "dev" ] # Se ejecuta cuando hay un push a la rama 'dev'

jobs:
  build:
    # 2. Definimos los sistemas operativos (la matriz)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    defaults:
      run:
        working-directory: ./framework

    steps:
      # 3. Descargar el código del repositorio
      - name: Check out Git repository
        uses: actions/checkout@v4

      # 4. Configurar Node.js (asegúrate de poner la versión que usas en tu proyecto)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '26.4.0'
          cache: 'npm' # Esto acelera futuras ejecuciones guardando las dependencias en caché
          cache-dependency-path: framework/package-lock.json # Le indica dónde buscar el archivo

      # 5. Instalar las dependencias del proyecto
      - name: Install Dependencies
        run: npm install # 'npm ci' es más seguro y rápido en CI que 'npm install'

      # NUEVO: 5.5 Descargar carpeta de assets pesados comprimidos
      - name: Descargar Assets
        # Usamos curl para descargar un archivo ZIP llamado archivos.zip y unzip para extraerlo
        # IMPORTANTE: Reemplaza "URL_AQUI" por el enlace de descarga directa de tu archivos.zip
        run: |
          curl -L "https://www.dropbox.com/scl/fi/md31cqwiwgq6k36e5xvm9/archivos.zip?rlkey=5vtg4vimh9i3uuog6zkliguig&st=23b2z7zu&dl=1" -o archivos.zip
          # Crea el directorio public si no existe y extrae el zip dentro. 
          # Al descomprimir se creará la carpeta public/assets porque está dentro del zip
          unzip -o archivos.zip -d public
          # Limpieza
          rm archivos.zip

      # 6. Compilar el código fuente (ej. Angular, React, etc., si es necesario)
      - name: Build Source
        run: npm run build

      # 7. Empaquetar Electron con electron-builder
      - name: Make/Distribute Electron App
        run: npx electron-builder --dir


      # 8. Subir los archivos generados como artefactos (para poder descargarlos desde GitHub)
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-app-${{ matrix.os }}
          # Usamos la carpeta configurada en package.json (release/)
          path: |
            framework/release/*.zip
